# Generated by Django 4.0.2 on 2022-02-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_data_contact_data_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
